// <auto-generated />
using System;
using DEPI.DAL.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260510130052_ChangePhoneNumberType")]
    partial class ChangePhoneNumberType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DEPI.DAL.Model.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasFilter("[ScheduleId] IS NOT NULL");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("ManagerSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ManagerSsn")
                        .IsUnique()
                        .HasFilter("[ManagerSsn] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Employee", b =>
                {
                    b.Property<string>("EmployeeSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("VacationBalance")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSsn");

                    b.HasIndex("ManagerSsn");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DEPI.DAL.Model.EmployeeDepartment", b =>
                {
                    b.Property<string>("EmployeeSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSsn", "DepartmentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("EmployeeDepartments");
                });

            modelBuilder.Entity("DEPI.DAL.Model.JopDescription", b =>
                {
                    b.Property<int>("JopDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JopDescriptionId"));

                    b.Property<string>("DailyTasks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductionId")
                        .HasColumnType("int");

                    b.Property<string>("RequiredCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JopDescriptionId");

                    b.HasIndex("ProductionId");

                    b.ToTable("JopDescriptions");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<string>("AuthorizedEmployeeSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoesOnEmployeeSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MissionId");

                    b.HasIndex("AuthorizedEmployeeSsn");

                    b.HasIndex("GoesOnEmployeeSsn");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("DEPI.DAL.Model.ProductionLine", b =>
                {
                    b.Property<int>("ProductionLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionLineId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductionLineId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("EmployeeSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("JopDescriptionId")
                        .HasColumnType("int");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("VacationRequestId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EmployeeSsn");

                    b.HasIndex("JopDescriptionId");

                    b.HasIndex("MissionId");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("VacationRequestId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("DEPI.DAL.Model.SwapRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("RecipientEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestingEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("RecipientEmployeeId");

                    b.HasIndex("RequestingEmployeeId");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasFilter("[ScheduleId] IS NOT NULL");

                    b.ToTable("SwapRequests");
                });

            modelBuilder.Entity("DEPI.DAL.Model.VacationRequest", b =>
                {
                    b.Property<int>("VacationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacationRequestId"));

                    b.Property<string>("EmployeeSsn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("VacationRequestId");

                    b.HasIndex("EmployeeSsn");

                    b.ToTable("VacationRequests");
                });

            modelBuilder.Entity("DEPI.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DEPI.DAL.Model.Attendance", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Schedule", "Schedule")
                        .WithOne("Attendance")
                        .HasForeignKey("DEPI.DAL.Model.Attendance", "ScheduleId");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Department", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Employee", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("DEPI.DAL.Model.Department", "ManagerSsn")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Employee", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerSsn")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.ProductionLine", "ProductionLine")
                        .WithMany("Employees")
                        .HasForeignKey("ProductionLineId");

                    b.HasOne("DEPI.DAL.Model.Shift", "Shift")
                        .WithMany("Employees")
                        .HasForeignKey("ShiftId");

                    b.HasOne("DEPI.DAL.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Employee")
                        .HasForeignKey("DEPI.DAL.Model.Employee", "UserId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Manager");

                    b.Navigation("ProductionLine");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("DEPI.DAL.Model.EmployeeDepartment", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Department", "Departments")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DEPI.DAL.Model.Employee", "Employees")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("EmployeeSsn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DEPI.DAL.Model.JopDescription", b =>
                {
                    b.HasOne("DEPI.DAL.Model.ProductionLine", "ProductionLine")
                        .WithMany("JopDescriptions")
                        .HasForeignKey("ProductionId");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Mission", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Employee", "AuthorizedEmployee")
                        .WithMany("AuthorizedMissions")
                        .HasForeignKey("AuthorizedEmployeeSsn")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.Employee", "GoesOnEmployee")
                        .WithMany("GoesOnMissions")
                        .HasForeignKey("GoesOnEmployeeSsn")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthorizedEmployee");

                    b.Navigation("GoesOnEmployee");
                });

            modelBuilder.Entity("DEPI.DAL.Model.ProductionLine", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Department", "Department")
                        .WithMany("ProductionLines")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Schedule", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeSsn");

                    b.HasOne("DEPI.DAL.Model.JopDescription", "JopDescription")
                        .WithMany("Schedules")
                        .HasForeignKey("JopDescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.Mission", "Mission")
                        .WithMany("Schedules")
                        .HasForeignKey("MissionId");

                    b.HasOne("DEPI.DAL.Model.ProductionLine", "ProductionLine")
                        .WithMany("Schedules")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.Shift", "Shift")
                        .WithMany("Schedules")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.VacationRequest", "VacationRequest")
                        .WithMany("Schedules")
                        .HasForeignKey("VacationRequestId");

                    b.Navigation("Employee");

                    b.Navigation("JopDescription");

                    b.Navigation("Mission");

                    b.Navigation("ProductionLine");

                    b.Navigation("Shift");

                    b.Navigation("VacationRequest");
                });

            modelBuilder.Entity("DEPI.DAL.Model.SwapRequest", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Employee", "RecipientEmployee")
                        .WithMany("ReceivedSwapRequests")
                        .HasForeignKey("RecipientEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.Employee", "RequestEmployee")
                        .WithMany("SentSwapRequests")
                        .HasForeignKey("RequestingEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DEPI.DAL.Model.Schedule", "Schedule")
                        .WithOne("SwapRequest")
                        .HasForeignKey("DEPI.DAL.Model.SwapRequest", "ScheduleId");

                    b.Navigation("RecipientEmployee");

                    b.Navigation("RequestEmployee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DEPI.DAL.Model.VacationRequest", b =>
                {
                    b.HasOne("DEPI.DAL.Model.Employee", "Employee")
                        .WithMany("VacationRequests")
                        .HasForeignKey("EmployeeSsn");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DEPI.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DEPI.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEPI.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DEPI.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DEPI.DAL.Model.Department", b =>
                {
                    b.Navigation("EmployeeDepartments");

                    b.Navigation("ProductionLines");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Employee", b =>
                {
                    b.Navigation("AuthorizedMissions");

                    b.Navigation("EmployeeDepartments");

                    b.Navigation("GoesOnMissions");

                    b.Navigation("ManagedDepartment")
                        .IsRequired();

                    b.Navigation("ReceivedSwapRequests");

                    b.Navigation("Schedules");

                    b.Navigation("SentSwapRequests");

                    b.Navigation("Subordinates");

                    b.Navigation("VacationRequests");
                });

            modelBuilder.Entity("DEPI.DAL.Model.JopDescription", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Mission", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DEPI.DAL.Model.ProductionLine", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("JopDescriptions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DEPI.DAL.Model.Schedule", b =>
                {
                    b.Navigation("Attendance")
                        .IsRequired();

                    b.Navigation("SwapRequest")
                        .IsRequired();
                });

            modelBuilder.Entity("DEPI.DAL.Model.Shift", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DEPI.DAL.Model.VacationRequest", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DEPI.DAL.Models.ApplicationUser", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
